### ISSUE TITLE
User Authentication Checklist

### ISSUE THREAD

**Issue by michelleamazinglin** [michelleamazinglin/Cloud#1]
### Functionality
- [x] The main button with logo should link to `/`
- [x]  Smooth, bug free navigation
***
### Before Login
- [x] The /login page should not display a link to Log In. Same for /signup
- [x]  Going to a random route `/#/wearethebest` should redirect or display a 404 page
- [x]  Errors should display for both /signup and /login.
- [x]  Errors should clear when moving between /signup and /login.
- [x]  Can sign up a user
- [x]  Can sign in as a user
- [x]  Can log out a user
- [x]  Can't sign up with the same username/email
***
### After Login
- [x] Should not be able to visit /login or /signup
- [x]  Should be able to refresh the page and still be logged in
***
### Style
- [x]  clouds represent posts
- [x]  cursor with a sun image
- [x]  When errors are displayed, most elements should not move around the page (particularly input boxes)
***
### Seeds
- [x] Adequate and appropriate seeds
